export const LANGUAGE = 'language';

export const languages = new Set([
  'xml', 'html', 'xhtml', 'rss', 'atom', 'xjb', 'xsd', 'xsl', 'plist', 'wsf', 'svg',
  'bash', 'sh',
  'c', 'h',
  'cpp', 'cc', 'c++', 'h++', 'hpp', 'hh', 'hxx', 'cxx',
  'csharp', 'cs', 'c#',
  'css',
  'markdown', 'md', 'mkdown', 'mkd',
  'diff', 'patch',
  'ruby', 'rb', 'gemspec', 'podspec', 'thor', 'irb',
  'go', 'golang',
  'ini', 'toml',
  'java', 'jsp',
  'javascript', 'js', 'jsx', 'mjs', 'cjs',
  'json',
  'kotlin', 'kt', 'kts',
  'less',
  'lua',
  'makefile', 'mk', 'mak', 'make',
  'perl', 'pl', 'pm',
  'objectivec', 'mm', 'objc', 'obj-c', 'obj-c++', 'objective-c++',
  'php',
  'php-template',
  'plaintext', 'text', 'txt',
  'python', 'py', 'gyp', 'ipython',
  'python-repl', 'pycon',
  'r',
  'rust', 'rs',
  'scss',
  'shell', 'console', 'shellsession',
  'sql',
  'swift',
  'yaml', 'yml',
  'typescript', 'ts', 'tsx',
  'vbnet', 'vb'
]);
